### ISSUE TITLE
Első bejelentkezés kezelése

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/simonyi-cimtar#11]
Az importálással felmerült a probléma, hogy bekerülnek olyan tagok, akikről nem áll rendelkezésre olyan információ, mint pl. az egyetem kezdési éve vagy a szakkoliba felvétel éve.

Azokat, akik léteznek az adatbázisban, mint tag, de nem léptek még be a rendszerbe (mert pl. az admin kézzel adta őket hozzá, vagy be lettek importálva), azok ugyanazt a profil adatbekérő lapot lássák, mint akik SSO-val először belépnek, előzetes regisztráció nélkül.

Így kitöltetjük velük a ténylegesen szükséges adatokat, miközben megvalósul a tagok importálása is.

Ezt egy last_login mezővel oldom meg, amely később is hasznos információt nyújt, egy first_login mezővel ellentétben.

**Comment by tmichel** [comment]
most minden requestre beírja újra a last_logint az aktuális dátumra. elég lenne ténylegesen a bejelentkezésnél ezt megcsinálni.

**Comment by vbalazs** [comment]
nem ártana, igen :shit:

**Comment by vbalazs** [comment]
csúnya megoldás, de lehet, hogy a last_login mezot atnevezem last_active-ra :D az a baj, hogy jelenleg nem latom azt, hogy hogyan lehetne megallapitani a konkrét bejelentkezes tényét

**Comment by tmichel** [comment]
igen ez tényleg nem triviális, nincs valami callbackünk az openssobol?

**Comment by vbalazs** [comment]
nincs, mert nem ennyire egyszerű a  production rendszer.
apache futtatja mod_passengerrel, az apache pedig shibbolethet használ az sso-val való kommunikációhoz. Az sso oldali szolgáltatás itt tényleg kimerül abban, hogy megvannak-e a megfelelő környezeti változók.
