### ISSUE TITLE
Ékezethelyes rendezés

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/simonyi-cimtar#17]
Jelenleg a nevek rendezésénél az 'Á' betűs emberek a lista végére kerülnek.
A ruby ebből a szempontból nagyon gyenge, egy gem van rá, ami áthidalja a problémát: https://github.com/k3rni/ffi-locale

WTF :shit:

**Comment by tmichel** [comment]
ez érdekes, mert elvileg ruby 1.9től full unicode support van. :)

**Comment by vbalazs** [comment]
nézd meg magad, pl, a kszk-ban Ács XXXX a lista végére kerül

**Comment by vbalazs** [comment]
lehet, hogy a postgres collate-tel van a baj, ezt még ki kell tesztelni rendesen.

**Comment by vbalazs** [comment]
``` bash
$ sudo apt-get install --no-install-recommends language-pack-hu
postgres@local:~$ createdb --template=template0 --encoding=utf8 --locale='hu_HU.utf8' -O szkcimtar szkcimtar
```
