### ISSUE TITLE
Autentikációs logika tesztjének rendberakása

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/simonyi-cimtar#21]
Jelenleg failel a teszt a #16 miatt, ennek javításához membershipek is szükségesek. A teszt usereket factory_girlösíteni kellene, megfelelő membershipekkel.

**Comment by tmichel** [comment]
ezzel együtt a fixture-ket is ki kell irtani. álljunk át teljesen a factory_girlre.
rails alap fixture generátorát is le kell cserélni, hogy factory_girl legyen helyette és generáljon rendes factory-kat

**Comment by vbalazs** [comment]
fixed in e2092f239
