### ISSUE TITLE
körök oldal átalakítás

### ISSUE THREAD

**Issue by tmichel** [kir-dev/simonyi-cimtar#24]
- tagok posztjai kerüljenek megjelenítésre
- linkek linkké tétele
- műveletek kerüljenek ki oldalra (csatlakozás, kilépés, szerkesztés stb.)
- jogok korlátozása: csak a körvezető tudjon megtenni bizonyos dolgokat:
  - kör adatainak szerkesztése
  - egy tag öregtaggá nyilvánítása
  - tagok posztjainak a szerkesztése
  - új tag elfogadása

**Comment by vbalazs** [comment]
még az értékeléseket ellenőrizni kell
