### ISSUE TITLE
encoding hiba a bejelentkezéskor

### ISSUE THREAD

**Issue by tmichel** [kir-dev/simonyi-cimtar#32]
```
Encoding::CompatibilityError (incompatible character encodings: ASCII-8BIT and UTF-8):
app/helpers/app_auth_helper.rb:33:in `include?'
app/helpers/app_auth_helper.rb:33:in `member_on_vir?'
app/controllers/application_controller.rb:87:in `authenticate_logic'
app/controllers/application_controller.rb:57:in `authenticate'
```

itt én arra gyanakszom, hogy a string példány, amivel összehasonlítjuk az `ENTITLEMENT_SZK`-t nem UTF-8 kódolású. lehet, hogy a szerver van rosszul konfigurálva.

jó lenne dev környezetben is reprodukálni.

**Comment by tmichel** [comment]
ez talán megoldja ([forrás](http://stackoverflow.com/a/9950029))

``` ruby
new_str = s.encode('utf-8', 'binary', :invalid => :replace, :undef => :replace, :replace => '')
```

**Comment by vbalazs** [comment]
mar hibat nem dob, de a login továbbra sem jó. gondoltam kilogolom az authentication első sorában a request environmentet (p request.env.inspect), de nem kerül a logba. ez a production miatt van? biztos, hogy meghivodik ott ("Redirected to https://szkcimtar.kirdev.sch.bme.hu/403
Filter chain halted as :authenticate rendered or redirected")

**Comment by tmichel** [comment]
ja szerintem production miatt van. nem 100%, de szerintem az `stdout` (ahova a `p` is ír) nincs átirányítva a logba. ha logolni akarsz akkor `Rails.logger.error "log message"` vagy ami jól esik, csak állítsd be a loggolási szintent.

**Comment by vbalazs** [comment]
> ez talán megoldja ([forrás](http://stackoverflow.com/a/9950029))
> 
> ``` ruby
> new_str = s.encode('utf-8', 'binary', :invalid => :replace, :undef => :replace, :replace => '')
> ```

Az a baj ezzel, hogy kivágja az ékezetes karaktereket: 

```
entitlement after encode=urn:geant:niif.hu:sch.bme.hu:entitlement:tag:Simonyi Kroly Szakkollgium:16;
```

**Comment by tmichel** [comment]
biztos vagyok benne, hogy érdemben át lehet konvertálni. a fenti kódrészlet értelemszerűen az invalid és nem definiált részeket kitörli. biztos fel lehet rendesen paraméterezni. nem néztem még annyira utána. de hosszútávon az nem jó megoldás, hogy egyesével a string változókat konvertálgatjuk. ezt valahol központilag kéne megoldani.

**Comment by vbalazs** [comment]
mint ahogy probalkoztam is a `config/environments/production.rb` fájlba a következő illesztésével:

``` ruby
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
```

persze nyilván nem számított semmit.

szerk:

``` ruby
entitlement = entitlement.force_encoding 'utf-8'
```

ez megjavította az entitlement ellenőrzést, de most meg a 

```
ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
    20:     <div class="control-group <%= form_input_feedback_css(@member, :full_name, 'error') %>">
    21:       <%= f.label :full_name, :class => 'control-label' %>
    22:       <div class="controls">
    23:         <%= f.text_field :full_name, :class => 'text_field' %>
    24:         <%= form_input_feedback_text(@member, :full_name) %>
    25:       </div>
    26:     </div>
  app/views/members/_form.html.erb:23:in `block in .......
```

ezek szerint az összes passengertől kapott környezeti változó ASCII kódolású

**Comment by vbalazs** [comment]
környezetből nem sikerült fixelni sehogy, javítottam kódból egyelőre. ez a megoldás problémát fog okozni (call force_encoding on nil class), ha majd lesz publikus, bejelentkezes nelkuli resze is az alkalmazasnak.
