### ISSUE TITLE
Keresés megvalósítása

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/simonyi-cimtar#4]
Keresés:
- tag teljes nevére
- tag becenevére
- tag sso login nevére
- tag munkahelyére (jelenlegi vagy volt)
- szervezeti egység teljes nevére
- szervezeti egység rövidítésére

jó lenne ilyen menő kereső, ami képes részegyezéseket is vizsgálni bárhol a megadott stringekben és vissza tudna adni több típusú találatot (pl. tag vagy szervezeti egység)

érdemes lenne megnézni a kapcsolódó railscastot: 
https://github.com/railscasts/111-advanced-search-form-revised 

és / vagy az elasticsearch-öt: https://github.com/elasticsearch/elasticsearch

**Comment by tmichel** [comment]
> Tamás Michelberger: még a munkahelyeknek kell egy listázós view
> Tamás Michelberger: ki kell találni, hogy mi legyen rajta. 
> Tamás Michelberger: talán azok a tagok akik ott dolgoztak valaha is.
