### ISSUE TITLE
öregtaggá váláskor nem érvénytelenednek a körre vonatkozó role-k

### ISSUE THREAD

**Issue by tmichel** [kir-dev/simonyi-cimtar#41]
mikor valaki egy körben öregtaggá válik, akkor az adott körben az összes pozíciója inaktívvá válik (`to` mezőt töltsük ki). valamint veszítse el az adott körre vonatkozó role-kat is.

**Comment by vbalazs** [comment]
reopen, forgot the tests...

**Comment by vbalazs** [comment]
@tmichel ehhez csinaltam meg a kodot, de nem tudom, hogy hogyan lehetne értelmesen tesztet írni hozz

**Comment by tmichel** [comment]
hétvégén megnézem.
