### ISSUE TITLE
lokalizálás pl role nevek

### ISSUE THREAD

**Issue by tmichel** [kir-dev/simonyi-cimtar#48]
van néhány felirat, ami "kiszivárog" az alkalmazáson belülről. ilyen például a role-k nevei. ezeket le kell fordítani és a magyar megfelelőjét kell a felületen megjeleníteni.

**Comment by vbalazs** [comment]
tudsz még ilyenről?

**Comment by vbalazs** [comment]
túl általános az issue, a konkrét para megoldva.

ha előjön még ilyen, akkor arról veszünk fel külön hibajegyet.
