### ISSUE TITLE
Globális posztok felvétele

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/simonyi-cimtar#6]
Van néhány különleges poszt, amikhez majd - egyelőre statikus, felületről nem szabályozható - jogosultságok tartoznak.

Ezek a posztok:
- admin
- elnök
- alelnök
- vezető
- vezető senior
- senior

ezek a posztok átnevezhetők legyenek a csoportokban (alias, pointer, kinek hogy tetszik), de nem törölhetők

**Comment by tmichel** [comment]
az egy bevezetendő globális kör miatt ez a probléma megoldódik. esetleg a telepítéshez és alapadatok felviteléhez valami scriptet érdemes lesz összeütni.

aliasok nem lesznek, mindig új posztot hozunk inkább létre, mert van lejárati dátumuk.
